<?php

namespace App\Services;

use App\Models\SignupInvite;
use App\Models\User;
use Illuminate\Support\Collection;
use Carbon\Carbon;

class SignupInviteService
{
    /**
     * Create a new signup invite.
     */
    public function createInvite(int $creatorId, ?int $expiresInHours = null): SignupInvite
    {
        $expiresAt = $expiresInHours !== null
            ? Carbon::now()->addHours($expiresInHours)
            : null;

        return SignupInvite::create([
            'token' => null, // Will be auto-generated by model boot
            'creator_id' => $creatorId,
            'expires_at' => $expiresAt,
        ]);
    }

    /**
     * Get all invites with creator and used_by relationships.
     */
    public function getAllInvites(): Collection
    {
        return SignupInvite::with(['creator', 'usedByUser'])
            ->latest()
            ->get();
    }

    /**
     * Get invite by token.
     */
    public function getByToken(string $token): ?SignupInvite
    {
        return SignupInvite::with(['creator', 'usedByUser'])
            ->where('token', $token)
            ->first();
    }

    /**
     * Validate if an invite token is valid for registration.
     * Returns array with 'valid' boolean and 'message' string.
     */
    public function validateToken(string $token): array
    {
        $invite = $this->getByToken($token);

        if (!$invite) {
            return [
                'valid' => false,
                'message' => 'Invalid invite token.',
                'invite' => null,
            ];
        }

        if ($invite->isUsed()) {
            return [
                'valid' => false,
                'message' => 'This invite link has already been used.',
                'invite' => $invite,
            ];
        }

        if ($invite->isExpired()) {
            return [
                'valid' => false,
                'message' => 'This invite link has expired.',
                'invite' => $invite,
            ];
        }

        return [
            'valid' => true,
            'message' => 'Invite token is valid.',
            'invite' => $invite,
        ];
    }

    /**
     * Use an invite token for registration.
     * Returns array with 'success' boolean, 'message' string, and 'invite' if successful.
     */
    public function useInvite(string $token, int $userId): array
    {
        $invite = $this->getByToken($token);

        if (!$invite) {
            return [
                'success' => false,
                'message' => 'Invalid invite token.',
            ];
        }

        if ($invite->isUsed()) {
            return [
                'success' => false,
                'message' => 'This invite link has already been used.',
            ];
        }

        if ($invite->isExpired()) {
            return [
                'success' => false,
                'message' => 'This invite link has expired.',
            ];
        }

        // Mark as used
        $invite->markAsUsed($userId);

        return [
            'success' => true,
            'message' => 'Invite token used successfully.',
            'invite' => $invite->fresh(),
        ];
    }

    /**
     * Get invites created by a specific user.
     */
    public function getInvitesByCreator(int $creatorId): Collection
    {
        return SignupInvite::with(['creator', 'usedByUser'])
            ->where('creator_id', $creatorId)
            ->latest()
            ->get();
    }

    /**
     * Get all valid (unused and unexpired) invites.
     */
    public function getValidInvites(): Collection
    {
        return SignupInvite::with(['creator', 'usedByUser'])
            ->whereNull('used_at')
            ->where(function ($query) {
                $query->whereNull('expires_at')
                      ->orWhere('expires_at', '>', Carbon::now());
            })
            ->latest()
            ->get();
    }

    /**
     * Get all used invites.
     */
    public function getUsedInvites(): Collection
    {
        return SignupInvite::with(['creator', 'usedByUser'])
            ->whereNotNull('used_at')
            ->latest('used_at')
            ->get();
    }

    /**
     * Get all expired invites.
     */
    public function getExpiredInvites(): Collection
    {
        return SignupInvite::with(['creator', 'usedByUser'])
            ->where(function ($query) {
                $query->where('expires_at', '<', Carbon::now())
                      ->orWhere(function ($q) {
                          $q->whereNotNull('expires_at')
                            ->whereNull('used_at');
                      });
            })
            ->latest()
            ->get();
    }
}
